version: '3.8'

services:
  # MySQL Database
  mysql-db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: e-commerce_db
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - e-commerce-network

networks:
  e-commerce-network:
    driver: bridge

volumes:
  mysql-data: